### ISSUE TITLE
Redisのエラーがヤバイ

### ISSUE THREAD

**Issue by shokai** [masuilab/slack-hubot#36]
こういうのが出まくってる

```
2015-01-09T07:12:33.537979+00:00 app[web.1]: node_redis: no callback to send error: OOM command not allowed when used memory > 'maxmemory'.
2015-01-09T07:12:33.539671+00:00 app[web.1]: [Fri Jan 09 2015 16:12:33 GMT+0900 (JST)] ERROR Error: OOM command not allowed when used memory > 'maxmemory'.
2015-01-09T07:12:33.539674+00:00 app[web.1]:   at ReplyParser.<anonymous> (/app/node_modules/hubot-scripts/node_modules/redis/index.js:279:27)
2015-01-09T07:12:33.539676+00:00 app[web.1]:   at ReplyParser.emit (events.js:95:17)
2015-01-09T07:12:33.539678+00:00 app[web.1]:   at ReplyParser.send_error (/app/node_modules/hubot-scripts/node_modules/redis/lib/parser/javascript.js:296:10)
2015-01-09T07:12:33.539679+00:00 app[web.1]:   at ReplyParser.execute (/app/node_modules/hubot-scripts/node_modules/redis/lib/parser/javascript.js:181:22)
2015-01-09T07:12:33.539681+00:00 app[web.1]:   at RedisClient.on_data (/app/node_modules/hubot-scripts/node_modules/redis/index.js:504:27)
2015-01-09T07:12:33.539682+00:00 app[web.1]:   at Socket.<anonymous> (/app/node_modules/hubot-scripts/node_modules/redis/index.js:82:14)
2015-01-09T07:12:33.539684+00:00 app[web.1]:   at Socket.emit (events.js:95:17)
2015-01-09T07:12:33.539685+00:00 app[web.1]:   at Socket.<anonymous> (_stream_readable.js:765:14)
2015-01-09T07:12:33.539687+00:00 app[web.1]:   at Socket.emit (events.js:92:17)
2015-01-09T07:12:33.539689+00:00 app[web.1]:   at emitReadable_ (_stream_readable.js:427:10)
2015-01-09T07:12:33.539690+00:00 app[web.1]:   at emitReadable (_stream_readable.js:423:5)
2015-01-09T07:12:33.539692+00:00 app[web.1]:   at readableAddChunk (_stream_readable.js:166:9)
2015-01-09T07:12:33.539693+00:00 app[web.1]:   at Socket.Readable.push (_stream_readable.js:128:10)
2015-01-09T07:12:33.539695+00:00 app[web.1]:   at TCP.onread (net.js:529:21)
```

**Comment by shokai** [comment]
redis、hubot-scripts npmのdependencyで入ってて、0.8.4が使われている。
今最新は[0.12.1](https://www.npmjs.com/package/redis)なのでアップデートする

**Comment by shokai** [comment]
特に効果なかった
よくわからない

**Comment by shokai** [comment]
そもそもredisに保存できない。hubotのbrainはredisに保存できなくてもオンメモリで持つから一見保存できてる風だけど、`heroku ps:restart`するとデータが巻き戻っている。

**Comment by shokai** [comment]
mongolabに移行しようと思う
[mongolab-brain](https://github.com/github/hubot-scripts/blob/master/src/scripts/mongolab-brain.coffee)がhubot-scriptsに入っていたので、これを使う

**Comment by shokai** [comment]
hubotのbrainの実装見ていると、持っているデータをシリアライズしてそのままredisに保存しようとしている。
毎回gyazzの本文データを何ページ分もまとめて保存しようとしていて、maxmemoryを超えているんだと思う

**Comment by shokai** [comment]
## hubot-rss-readerに登録し直す

```json
{
 "news": [
   "http://b.hatena.ne.jp/shokai/rss",
   "http://blog.geta6.net/rss",
   "http://blog.keroxp.me/feed",
   "http://blog.sota1235.com/feed",
   "http://feeds.feedburner.com/gadget-shot/feed",
   "http://fukuda56513.hatenablog.jp/feed",
   "http://linka.jp/feed",
   "http://masui.blog.jp/index.rdf",
   "http://nikezono.net/rss",
   "http://note.nekobato.net/rss",
   "http://qiita.com/geta6/feed",
   "http://qiita.com/keroxp/feed",
   "http://shokai.org/blog/feed",
   "http://snuke.hatenablog.com/feed",
   "http://sota1235.com/feed.xml",
   "http://stkay.hateblo.jp/feed",
   "http://ytanaka.org/atom.xml",
   "https://github.com/Hikaru-Ito.atom",
   "https://github.com/TakumiBaba.atom",
   "https://github.com/akiroom.atom",
   "https://github.com/geta6.atom",
   "https://github.com/hryk.atom",
   "https://github.com/keimakai.atom",
   "https://github.com/keroxp.atom",
   "https://github.com/marutaru.atom",
   "https://github.com/masui.atom",
   "https://github.com/mosya.atom",
   "https://github.com/myatsumoto.atom",
   "https://github.com/napo0703.atom",
   "https://github.com/nekobato.atom",
   "https://github.com/nikezono.atom",
   "https://github.com/organizations/masuilab/shokai.private.atom?token=AACFnEVQZX6zJPXQHUz6SSUpZ1nl1rwHks6yeHn_wA==",
   "https://github.com/shao1555.atom",
   "https://github.com/shokai.atom",
   "https://github.com/snukent.atom",
   "https://github.com/sota1235.atom",
   "https://github.com/stkay.atom",
   "https://github.com/yoshihisa56513.atom",
   "https://github.com/ytanaka-.atom",
   "https://github.com/zakuni.atom"
 ],
 "hubot": [
   "https://github.com/nikezono/hubot-coveralls/commits/master.atom",
   "https://github.com/nikezono/node-find-rss/commits/master.atom",
   "https://github.com/shokai/hubot-rss-reader/commits/master.atom"
 ],
 "technews": [
   "http://b.hatena.ne.jp/naoya/rss",
   "http://blog.nodejs.org/feed/",
   "http://feeds.delicious.com/v2/rss/miyagawa",
   "http://github-trends.ryotarai.info/rss/github_trends_all_daily.rss",
   "http://jser.info/rss/",
   "http://jxck.hatenablog.com/feed",
   "http://sengoku-akb.jugem.jp/?mode=rss",
   "http://yosuke-furukawa.hatenablog.com/feed"
 ],
 "test": [
   "http://shokai.org/blog/feed"
 ],
 "real_ui": [],
 "rive": [],
 "unific": [],
 "nikezonotify": [],
 "unific_masuilab": [
   "http://www.unific.net/masuilab/rss"
 ],
 "shookai": [],
 "ytanakaselect": [
   "http://b.hatena.ne.jp/Constellation/rss",
   "http://b.hatena.ne.jp/byrdland1956/rss",
   "http://b.hatena.ne.jp/dai_yamashita/rss",
   "http://b.hatena.ne.jp/efcl/rss",
   "http://b.hatena.ne.jp/makotot-riceball/rss",
   "http://b.hatena.ne.jp/mizchi/rss",
   "http://b.hatena.ne.jp/moznion/rss",
   "http://b.hatena.ne.jp/n2s/rss",
   "http://b.hatena.ne.jp/naoya/rss",
   "http://b.hatena.ne.jp/pocotan001/rss",
   "http://b.hatena.ne.jp/side_tana/rss",
   "http://b.hatena.ne.jp/toma-stk/rss",
   "http://b.hatena.ne.jp/turusuke_0/rss",
   "http://b.hatena.ne.jp/vespresso/rss",
   "http://b.hatena.ne.jp/vvakame/rss"
 ],
 "osusume": []
}
```

**Comment by shokai** [comment]
mongolab、保存するとエラー出る

```
2015-01-10T13:45:25.323317+00:00 app[web.1]: [Sat Jan 10 2015 22:45:25 GMT+0900 (JST)] ERROR Received error [object Object]
2015-01-10T13:45:25.323513+00:00 app[web.1]: [Sat Jan 10 2015 22:45:25 GMT+0900 (JST)] ERROR undefined
2015-01-10T13:45:25.323579+00:00 app[web.1]: [Sat Jan 10 2015 22:45:25 GMT+0900 (JST)] ERROR Exiting in 1 second
2015-01-10T13:45:25.323996+00:00 app[web.1]: [Sat Jan 10 2015 22:45:25 GMT+0900 (JST)] ERROR Received error [object Object]
2015-01-10T13:45:25.324057+00:00 app[web.1]: [Sat Jan 10 2015 22:45:25 GMT+0900 (JST)] ERROR undefined
2015-01-10T13:45:25.324096+00:00 app[web.1]: [Sat Jan 10 2015 22:45:25 GMT+0900 (JST)] ERROR Exiting in 1 second
```

**Comment by shokai** [comment]
これはslackアダプタの問題だった。連続して何十件もsendするとプロセスごと死ぬ。

**Comment by shokai** [comment]
mongolab-brainも1つのドキュメントに全dataをシリアライズして突っ込んでいるので、redis-brain-hashにしよう
https://www.npmjs.com/package/hubot-brain-redis-hash

**Comment by shokai** [comment]
たぶんokだと思う
前のredisのデータを消せたら消したい

**Comment by shokai** [comment]
消した https://dashboard.heroku.com/apps/masuilab-hubot2/resources

```coffee
use strict'

Redis = require 'redis'
Url   = require 'url'

info   = Url.parse process.env.REDISTOGO_URL
client = Redis.createClient(info.port, info.hostname)
prefix = info.path?.replace('/', '') or 'hubot'

if info.auth
  client.auth info.auth.split(":")[1]


  client.on 'error', (err) ->
    console.error err

  client.on 'connect', ->
    console.log 'connect!'

    client.get "#{prefix}:storage", (err, reply) ->
      return console.error err if err

      if reply
        data = JSON.parse reply.toString()
        console.log Object.keys data._private

      client.del "#{prefix}:storage", (err) ->
        return console.error err if err
        console.log 'deleted'
```
