### ISSUE TITLE
message以外がstarされるとslack-starが強制終了する

### ISSUE THREAD

**Issue by shokai** [masuilab/slack-hubot#38]
starってmessageだけじゃなくて、fileとfile_commentとchannelもstarできて、同じstar_addedやstar_removedイベントで流れてくるらしい。
https://api.slack.com/methods/stars.list

`item.type is 'message'`とかで判断すれば良さそう

## channelをstarした時
```
  hubot:slack-star { type: 'star_removed', user: 'U02AGHF5Y', item: { type: 'channel', channel: 'C02AGHXRW' }, event_ts: '1422668932.751092' } +0ms
[Sat Jan 31 2015 10:48:52 GMT+0900 (JST)] ERROR TypeError: Cannot read property 'permalink' of undefined
  at Client.<anonymous> (/Users/sho/src/nodejs/hubot/shokaibot/scripts/slack-star.coffee:34:42)
  at Client.emit (events.js:95:17)
  at Client.onMessage (/Users/sho/src/nodejs/hubot/slack-client/src/client.js:406:10)
  at WebSocket.<anonymous> (/Users/sho/src/nodejs/hubot/slack-client/src/client.js:141:24)
  at WebSocket.emit (events.js:98:17)
  at Receiver.self._receiver.ontext (/Users/sho/src/nodejs/hubot/slack-client/node_modules/ws/lib/WebSocket.js:697:10)
  at Receiver.opcodes.1.finish (/Users/sho/src/nodejs/hubot/slack-client/node_modules/ws/lib/Receiver.js:397:14)
  at Receiver.expectHandler (/Users/sho/src/nodejs/hubot/slack-client/node_modules/ws/lib/Receiver.js:384:31)
  at Receiver.add (/Users/sho/src/nodejs/hubot/slack-client/node_modules/ws/lib/Receiver.js:93:24)
  at CleartextStream.firstHandler (/Users/sho/src/nodejs/hubot/slack-client/node_modules/ws/lib/WebSocket.js:678:22)
  at CleartextStream.emit (events.js:95:17)
  at CleartextStream.<anonymous> (_stream_readable.js:764:14)
  at CleartextStream.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:426:10)
  at _stream_readable.js:419:7
  at process._tickCallback (node.js:419:13)

[TypeError: Cannot read property 'permalink' of undefined]
[Sat Jan 31 2015 10:49:00 GMT+0900 (JST)] ERROR Last pong is too old: 10.594
[Sat Jan 31 2015 10:49:00 GMT+0900 (JST)] INFO Reconnecting in 1000ms
[Sat Jan 31 2015 10:49:00 GMT+0900 (JST)] INFO Slack client closed
```

**Comment by shokai** [comment]
解決
